# Generated by Django 3.2.13 on 2023-09-23 14:01

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=45, verbose_name='user_id')),
                ('user', models.CharField(max_length=45, verbose_name='Usuário')),
                ('data_registro', models.DateField(help_text='Data em que foi visualizada a praga.', verbose_name='Data da Ocorrência')),
                ('praga', models.CharField(choices=[], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40)),
                ('Cultura', models.CharField(choices=[], help_text='Qual plantação foi contaminada?', max_length=45)),
                ('status', models.CharField(choices=[('s', 'Sim'), ('N', 'Não')], help_text='A praga esta controlada?', max_length=45, verbose_name='Controlada?')),
                ('nome_propriedade', models.CharField(help_text='Nome da propriedade que esta sendo contaminada.', max_length=60, verbose_name='Nome da Propriedade afetada')),
                ('prejuizo', models.DecimalField(decimal_places=2, default=0.0, help_text='qual o valor do prejuizo?', max_digits=20, verbose_name='Total do prejuizo R$')),
                ('hectares', models.IntegerField(default=0, help_text='quantos hectares estão contaminados', verbose_name='Quantidade de hectar afetado')),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('imagens', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Selecione as imagens da praga.', null=True, upload_to='images', variations={}, verbose_name='Imagem')),
                ('Observações', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tabela de Ocorrência',
                'verbose_name_plural': 'Tabela de Ocorrência',
            },
        ),
        migrations.CreateModel(
            name='Tb_Registros',
            fields=[
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(editable=False, max_length=45)),
                ('praga', models.CharField(choices=[], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40)),
                ('cultura', models.CharField(choices=[], help_text='Qual plantação foi contaminada?', max_length=45, verbose_name='Cultura')),
                ('status', models.CharField(choices=[('s', 'Sim'), ('N', 'Não')], help_text='A praga esta controlada?', max_length=45, verbose_name='A Praga Esta Controlada?')),
                ('nome_propriedade', models.CharField(blank=True, help_text='Nome da propriedade que esta sendo contaminada.', max_length=60, null=True, verbose_name='Nome da Propriedade:')),
                ('prejuizo', models.DecimalField(decimal_places=2, default=0.0, help_text='qual o valor do prejuizo?', max_digits=20, verbose_name='Total do prejuizo R$')),
                ('hectares', models.IntegerField(default=0, help_text='quantos hectares estão contaminados', verbose_name='Quantidade de hectar afetado')),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, help_text='Selecione as imagens da praga.', null=True, upload_to='images', variations={'thumbnail': {'crop': True, 'height': 400, 'width': 300}}, verbose_name='Imagem')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Tabela de Registro',
                'verbose_name_plural': 'Tabela de Registros',
            },
        ),
    ]
