# Generated by Django 3.2.13 on 2023-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbculturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cultura', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Tabela de Culturas',
                'verbose_name_plural': 'Tabela de Culturas',
            },
        ),
    ]
