# Generated by Django 3.2.13 on 2023-09-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tbculturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpragas',
            name='cultura',
        ),
        migrations.RemoveField(
            model_name='tbpragas',
            name='nome_comum2',
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='Cultura',
            field=models.CharField(choices=[('laranja', 'laranja'), ('maça', 'maça')], help_text='Qual plantação foi contaminada?', max_length=45),
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='praga',
            field=models.CharField(choices=[('dsd', 'dsd')], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tb_registros',
            name='cultura',
            field=models.CharField(choices=[('laranja', 'laranja'), ('maça', 'maça')], help_text='Qual plantação foi contaminada?', max_length=45, verbose_name='Cultura'),
        ),
        migrations.AlterField(
            model_name='tb_registros',
            name='praga',
            field=models.CharField(choices=[('dsd', 'dsd')], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tbpragas',
            name='especie',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
