# Generated by Django 3.2.13 on 2023-09-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230923_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencias',
            name='inserido',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='tb_registros',
            name='inserido',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='ocorrencias',
            name='praga',
            field=models.CharField(choices=[('varejeira', 'varejeira')], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40),
        ),
        migrations.AlterField(
            model_name='tb_registros',
            name='praga',
            field=models.CharField(choices=[('varejeira', 'varejeira')], help_text='Selecione qual o tipo de praga esta contaminando.', max_length=40),
        ),
    ]
